// Code generated by ent, DO NOT EDIT.

package sharedloan

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the sharedloan type in the database.
	Label = "shared_loan"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldLoanID holds the string denoting the loan_id field in the database.
	FieldLoanID = "loan_id"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeLoan holds the string denoting the loan edge name in mutations.
	EdgeLoan = "loan"
	// Table holds the table name of the sharedloan in the database.
	Table = "shared_loans"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "shared_loans"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// LoanTable is the table that holds the loan relation/edge.
	LoanTable = "shared_loans"
	// LoanInverseTable is the table name for the Loan entity.
	// It exists in this package in order to avoid circular dependency with the "loan" package.
	LoanInverseTable = "loans"
	// LoanColumn is the table column denoting the loan relation/edge.
	LoanColumn = "loan_id"
)

// Columns holds all SQL columns for sharedloan fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldLoanID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the SharedLoan queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByLoanID orders the results by the loan_id field.
func ByLoanID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLoanID, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByLoanField orders the results by loan field.
func ByLoanField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLoanStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newLoanStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LoanInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, LoanTable, LoanColumn),
	)
}
