// Code generated by ent, DO NOT EDIT.

package sharedloan

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/crusyn/loans/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.SharedLoan {
	return predicate.SharedLoan(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SharedLoan {
	return predicate.SharedLoan(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SharedLoan {
	return predicate.SharedLoan(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SharedLoan {
	return predicate.SharedLoan(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SharedLoan {
	return predicate.SharedLoan(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SharedLoan {
	return predicate.SharedLoan(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SharedLoan {
	return predicate.SharedLoan(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SharedLoan {
	return predicate.SharedLoan(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SharedLoan {
	return predicate.SharedLoan(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.SharedLoan {
	return predicate.SharedLoan(sql.FieldEQ(FieldUserID, v))
}

// LoanID applies equality check predicate on the "loan_id" field. It's identical to LoanIDEQ.
func LoanID(v int) predicate.SharedLoan {
	return predicate.SharedLoan(sql.FieldEQ(FieldLoanID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.SharedLoan {
	return predicate.SharedLoan(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.SharedLoan {
	return predicate.SharedLoan(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.SharedLoan {
	return predicate.SharedLoan(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.SharedLoan {
	return predicate.SharedLoan(sql.FieldNotIn(FieldUserID, vs...))
}

// LoanIDEQ applies the EQ predicate on the "loan_id" field.
func LoanIDEQ(v int) predicate.SharedLoan {
	return predicate.SharedLoan(sql.FieldEQ(FieldLoanID, v))
}

// LoanIDNEQ applies the NEQ predicate on the "loan_id" field.
func LoanIDNEQ(v int) predicate.SharedLoan {
	return predicate.SharedLoan(sql.FieldNEQ(FieldLoanID, v))
}

// LoanIDIn applies the In predicate on the "loan_id" field.
func LoanIDIn(vs ...int) predicate.SharedLoan {
	return predicate.SharedLoan(sql.FieldIn(FieldLoanID, vs...))
}

// LoanIDNotIn applies the NotIn predicate on the "loan_id" field.
func LoanIDNotIn(vs ...int) predicate.SharedLoan {
	return predicate.SharedLoan(sql.FieldNotIn(FieldLoanID, vs...))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.SharedLoan {
	return predicate.SharedLoan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.SharedLoan {
	return predicate.SharedLoan(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLoan applies the HasEdge predicate on the "loan" edge.
func HasLoan() predicate.SharedLoan {
	return predicate.SharedLoan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, LoanTable, LoanColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLoanWith applies the HasEdge predicate on the "loan" edge with a given conditions (other predicates).
func HasLoanWith(preds ...predicate.Loan) predicate.SharedLoan {
	return predicate.SharedLoan(func(s *sql.Selector) {
		step := newLoanStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SharedLoan) predicate.SharedLoan {
	return predicate.SharedLoan(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SharedLoan) predicate.SharedLoan {
	return predicate.SharedLoan(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SharedLoan) predicate.SharedLoan {
	return predicate.SharedLoan(sql.NotPredicates(p))
}
