// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/crusyn/loans/ent/loan"
	"github.com/crusyn/loans/ent/sharedloan"
	"github.com/crusyn/loans/ent/user"
)

// LoanCreate is the builder for creating a Loan entity.
type LoanCreate struct {
	config
	mutation *LoanMutation
	hooks    []Hook
}

// SetAmount sets the "amount" field.
func (lc *LoanCreate) SetAmount(i int) *LoanCreate {
	lc.mutation.SetAmount(i)
	return lc
}

// SetRate sets the "rate" field.
func (lc *LoanCreate) SetRate(f float64) *LoanCreate {
	lc.mutation.SetRate(f)
	return lc
}

// SetTerm sets the "term" field.
func (lc *LoanCreate) SetTerm(i int) *LoanCreate {
	lc.mutation.SetTerm(i)
	return lc
}

// SetBorrowerID sets the "borrower_id" field.
func (lc *LoanCreate) SetBorrowerID(i int) *LoanCreate {
	lc.mutation.SetBorrowerID(i)
	return lc
}

// SetBorrower sets the "borrower" edge to the User entity.
func (lc *LoanCreate) SetBorrower(u *User) *LoanCreate {
	return lc.SetBorrowerID(u.ID)
}

// AddSharedLoanIDs adds the "shared_loan" edge to the SharedLoan entity by IDs.
func (lc *LoanCreate) AddSharedLoanIDs(ids ...int) *LoanCreate {
	lc.mutation.AddSharedLoanIDs(ids...)
	return lc
}

// AddSharedLoan adds the "shared_loan" edges to the SharedLoan entity.
func (lc *LoanCreate) AddSharedLoan(s ...*SharedLoan) *LoanCreate {
	ids := make([]int, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return lc.AddSharedLoanIDs(ids...)
}

// Mutation returns the LoanMutation object of the builder.
func (lc *LoanCreate) Mutation() *LoanMutation {
	return lc.mutation
}

// Save creates the Loan in the database.
func (lc *LoanCreate) Save(ctx context.Context) (*Loan, error) {
	return withHooks(ctx, lc.sqlSave, lc.mutation, lc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (lc *LoanCreate) SaveX(ctx context.Context) *Loan {
	v, err := lc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (lc *LoanCreate) Exec(ctx context.Context) error {
	_, err := lc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lc *LoanCreate) ExecX(ctx context.Context) {
	if err := lc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (lc *LoanCreate) check() error {
	if _, ok := lc.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "Loan.amount"`)}
	}
	if _, ok := lc.mutation.Rate(); !ok {
		return &ValidationError{Name: "rate", err: errors.New(`ent: missing required field "Loan.rate"`)}
	}
	if _, ok := lc.mutation.Term(); !ok {
		return &ValidationError{Name: "term", err: errors.New(`ent: missing required field "Loan.term"`)}
	}
	if _, ok := lc.mutation.BorrowerID(); !ok {
		return &ValidationError{Name: "borrower_id", err: errors.New(`ent: missing required field "Loan.borrower_id"`)}
	}
	if _, ok := lc.mutation.BorrowerID(); !ok {
		return &ValidationError{Name: "borrower", err: errors.New(`ent: missing required edge "Loan.borrower"`)}
	}
	return nil
}

func (lc *LoanCreate) sqlSave(ctx context.Context) (*Loan, error) {
	if err := lc.check(); err != nil {
		return nil, err
	}
	_node, _spec := lc.createSpec()
	if err := sqlgraph.CreateNode(ctx, lc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	lc.mutation.id = &_node.ID
	lc.mutation.done = true
	return _node, nil
}

func (lc *LoanCreate) createSpec() (*Loan, *sqlgraph.CreateSpec) {
	var (
		_node = &Loan{config: lc.config}
		_spec = sqlgraph.NewCreateSpec(loan.Table, sqlgraph.NewFieldSpec(loan.FieldID, field.TypeInt))
	)
	if value, ok := lc.mutation.Amount(); ok {
		_spec.SetField(loan.FieldAmount, field.TypeInt, value)
		_node.Amount = value
	}
	if value, ok := lc.mutation.Rate(); ok {
		_spec.SetField(loan.FieldRate, field.TypeFloat64, value)
		_node.Rate = value
	}
	if value, ok := lc.mutation.Term(); ok {
		_spec.SetField(loan.FieldTerm, field.TypeInt, value)
		_node.Term = value
	}
	if nodes := lc.mutation.BorrowerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   loan.BorrowerTable,
			Columns: []string{loan.BorrowerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.BorrowerID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := lc.mutation.SharedLoanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   loan.SharedLoanTable,
			Columns: []string{loan.SharedLoanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(sharedloan.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// LoanCreateBulk is the builder for creating many Loan entities in bulk.
type LoanCreateBulk struct {
	config
	err      error
	builders []*LoanCreate
}

// Save creates the Loan entities in the database.
func (lcb *LoanCreateBulk) Save(ctx context.Context) ([]*Loan, error) {
	if lcb.err != nil {
		return nil, lcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(lcb.builders))
	nodes := make([]*Loan, len(lcb.builders))
	mutators := make([]Mutator, len(lcb.builders))
	for i := range lcb.builders {
		func(i int, root context.Context) {
			builder := lcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LoanMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, lcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, lcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, lcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (lcb *LoanCreateBulk) SaveX(ctx context.Context) []*Loan {
	v, err := lcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (lcb *LoanCreateBulk) Exec(ctx context.Context) error {
	_, err := lcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lcb *LoanCreateBulk) ExecX(ctx context.Context) {
	if err := lcb.Exec(ctx); err != nil {
		panic(err)
	}
}
