// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/crusyn/loans/ent/loan"
	"github.com/crusyn/loans/ent/predicate"
	"github.com/crusyn/loans/ent/user"
)

// LoanUpdate is the builder for updating Loan entities.
type LoanUpdate struct {
	config
	hooks    []Hook
	mutation *LoanMutation
}

// Where appends a list predicates to the LoanUpdate builder.
func (lu *LoanUpdate) Where(ps ...predicate.Loan) *LoanUpdate {
	lu.mutation.Where(ps...)
	return lu
}

// SetAmount sets the "amount" field.
func (lu *LoanUpdate) SetAmount(i int) *LoanUpdate {
	lu.mutation.ResetAmount()
	lu.mutation.SetAmount(i)
	return lu
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (lu *LoanUpdate) SetNillableAmount(i *int) *LoanUpdate {
	if i != nil {
		lu.SetAmount(*i)
	}
	return lu
}

// AddAmount adds i to the "amount" field.
func (lu *LoanUpdate) AddAmount(i int) *LoanUpdate {
	lu.mutation.AddAmount(i)
	return lu
}

// SetRate sets the "rate" field.
func (lu *LoanUpdate) SetRate(f float64) *LoanUpdate {
	lu.mutation.ResetRate()
	lu.mutation.SetRate(f)
	return lu
}

// SetNillableRate sets the "rate" field if the given value is not nil.
func (lu *LoanUpdate) SetNillableRate(f *float64) *LoanUpdate {
	if f != nil {
		lu.SetRate(*f)
	}
	return lu
}

// AddRate adds f to the "rate" field.
func (lu *LoanUpdate) AddRate(f float64) *LoanUpdate {
	lu.mutation.AddRate(f)
	return lu
}

// SetTerm sets the "term" field.
func (lu *LoanUpdate) SetTerm(i int) *LoanUpdate {
	lu.mutation.ResetTerm()
	lu.mutation.SetTerm(i)
	return lu
}

// SetNillableTerm sets the "term" field if the given value is not nil.
func (lu *LoanUpdate) SetNillableTerm(i *int) *LoanUpdate {
	if i != nil {
		lu.SetTerm(*i)
	}
	return lu
}

// AddTerm adds i to the "term" field.
func (lu *LoanUpdate) AddTerm(i int) *LoanUpdate {
	lu.mutation.AddTerm(i)
	return lu
}

// SetBorrowerID sets the "borrower_id" field.
func (lu *LoanUpdate) SetBorrowerID(i int) *LoanUpdate {
	lu.mutation.SetBorrowerID(i)
	return lu
}

// SetNillableBorrowerID sets the "borrower_id" field if the given value is not nil.
func (lu *LoanUpdate) SetNillableBorrowerID(i *int) *LoanUpdate {
	if i != nil {
		lu.SetBorrowerID(*i)
	}
	return lu
}

// SetBorrower sets the "borrower" edge to the User entity.
func (lu *LoanUpdate) SetBorrower(u *User) *LoanUpdate {
	return lu.SetBorrowerID(u.ID)
}

// Mutation returns the LoanMutation object of the builder.
func (lu *LoanUpdate) Mutation() *LoanMutation {
	return lu.mutation
}

// ClearBorrower clears the "borrower" edge to the User entity.
func (lu *LoanUpdate) ClearBorrower() *LoanUpdate {
	lu.mutation.ClearBorrower()
	return lu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (lu *LoanUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, lu.sqlSave, lu.mutation, lu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (lu *LoanUpdate) SaveX(ctx context.Context) int {
	affected, err := lu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (lu *LoanUpdate) Exec(ctx context.Context) error {
	_, err := lu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (lu *LoanUpdate) ExecX(ctx context.Context) {
	if err := lu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (lu *LoanUpdate) check() error {
	if _, ok := lu.mutation.BorrowerID(); lu.mutation.BorrowerCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Loan.borrower"`)
	}
	return nil
}

func (lu *LoanUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := lu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(loan.Table, loan.Columns, sqlgraph.NewFieldSpec(loan.FieldID, field.TypeInt))
	if ps := lu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := lu.mutation.Amount(); ok {
		_spec.SetField(loan.FieldAmount, field.TypeInt, value)
	}
	if value, ok := lu.mutation.AddedAmount(); ok {
		_spec.AddField(loan.FieldAmount, field.TypeInt, value)
	}
	if value, ok := lu.mutation.Rate(); ok {
		_spec.SetField(loan.FieldRate, field.TypeFloat64, value)
	}
	if value, ok := lu.mutation.AddedRate(); ok {
		_spec.AddField(loan.FieldRate, field.TypeFloat64, value)
	}
	if value, ok := lu.mutation.Term(); ok {
		_spec.SetField(loan.FieldTerm, field.TypeInt, value)
	}
	if value, ok := lu.mutation.AddedTerm(); ok {
		_spec.AddField(loan.FieldTerm, field.TypeInt, value)
	}
	if lu.mutation.BorrowerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   loan.BorrowerTable,
			Columns: []string{loan.BorrowerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := lu.mutation.BorrowerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   loan.BorrowerTable,
			Columns: []string{loan.BorrowerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, lu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{loan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	lu.mutation.done = true
	return n, nil
}

// LoanUpdateOne is the builder for updating a single Loan entity.
type LoanUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LoanMutation
}

// SetAmount sets the "amount" field.
func (luo *LoanUpdateOne) SetAmount(i int) *LoanUpdateOne {
	luo.mutation.ResetAmount()
	luo.mutation.SetAmount(i)
	return luo
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (luo *LoanUpdateOne) SetNillableAmount(i *int) *LoanUpdateOne {
	if i != nil {
		luo.SetAmount(*i)
	}
	return luo
}

// AddAmount adds i to the "amount" field.
func (luo *LoanUpdateOne) AddAmount(i int) *LoanUpdateOne {
	luo.mutation.AddAmount(i)
	return luo
}

// SetRate sets the "rate" field.
func (luo *LoanUpdateOne) SetRate(f float64) *LoanUpdateOne {
	luo.mutation.ResetRate()
	luo.mutation.SetRate(f)
	return luo
}

// SetNillableRate sets the "rate" field if the given value is not nil.
func (luo *LoanUpdateOne) SetNillableRate(f *float64) *LoanUpdateOne {
	if f != nil {
		luo.SetRate(*f)
	}
	return luo
}

// AddRate adds f to the "rate" field.
func (luo *LoanUpdateOne) AddRate(f float64) *LoanUpdateOne {
	luo.mutation.AddRate(f)
	return luo
}

// SetTerm sets the "term" field.
func (luo *LoanUpdateOne) SetTerm(i int) *LoanUpdateOne {
	luo.mutation.ResetTerm()
	luo.mutation.SetTerm(i)
	return luo
}

// SetNillableTerm sets the "term" field if the given value is not nil.
func (luo *LoanUpdateOne) SetNillableTerm(i *int) *LoanUpdateOne {
	if i != nil {
		luo.SetTerm(*i)
	}
	return luo
}

// AddTerm adds i to the "term" field.
func (luo *LoanUpdateOne) AddTerm(i int) *LoanUpdateOne {
	luo.mutation.AddTerm(i)
	return luo
}

// SetBorrowerID sets the "borrower_id" field.
func (luo *LoanUpdateOne) SetBorrowerID(i int) *LoanUpdateOne {
	luo.mutation.SetBorrowerID(i)
	return luo
}

// SetNillableBorrowerID sets the "borrower_id" field if the given value is not nil.
func (luo *LoanUpdateOne) SetNillableBorrowerID(i *int) *LoanUpdateOne {
	if i != nil {
		luo.SetBorrowerID(*i)
	}
	return luo
}

// SetBorrower sets the "borrower" edge to the User entity.
func (luo *LoanUpdateOne) SetBorrower(u *User) *LoanUpdateOne {
	return luo.SetBorrowerID(u.ID)
}

// Mutation returns the LoanMutation object of the builder.
func (luo *LoanUpdateOne) Mutation() *LoanMutation {
	return luo.mutation
}

// ClearBorrower clears the "borrower" edge to the User entity.
func (luo *LoanUpdateOne) ClearBorrower() *LoanUpdateOne {
	luo.mutation.ClearBorrower()
	return luo
}

// Where appends a list predicates to the LoanUpdate builder.
func (luo *LoanUpdateOne) Where(ps ...predicate.Loan) *LoanUpdateOne {
	luo.mutation.Where(ps...)
	return luo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (luo *LoanUpdateOne) Select(field string, fields ...string) *LoanUpdateOne {
	luo.fields = append([]string{field}, fields...)
	return luo
}

// Save executes the query and returns the updated Loan entity.
func (luo *LoanUpdateOne) Save(ctx context.Context) (*Loan, error) {
	return withHooks(ctx, luo.sqlSave, luo.mutation, luo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (luo *LoanUpdateOne) SaveX(ctx context.Context) *Loan {
	node, err := luo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (luo *LoanUpdateOne) Exec(ctx context.Context) error {
	_, err := luo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (luo *LoanUpdateOne) ExecX(ctx context.Context) {
	if err := luo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (luo *LoanUpdateOne) check() error {
	if _, ok := luo.mutation.BorrowerID(); luo.mutation.BorrowerCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Loan.borrower"`)
	}
	return nil
}

func (luo *LoanUpdateOne) sqlSave(ctx context.Context) (_node *Loan, err error) {
	if err := luo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(loan.Table, loan.Columns, sqlgraph.NewFieldSpec(loan.FieldID, field.TypeInt))
	id, ok := luo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Loan.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := luo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, loan.FieldID)
		for _, f := range fields {
			if !loan.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != loan.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := luo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := luo.mutation.Amount(); ok {
		_spec.SetField(loan.FieldAmount, field.TypeInt, value)
	}
	if value, ok := luo.mutation.AddedAmount(); ok {
		_spec.AddField(loan.FieldAmount, field.TypeInt, value)
	}
	if value, ok := luo.mutation.Rate(); ok {
		_spec.SetField(loan.FieldRate, field.TypeFloat64, value)
	}
	if value, ok := luo.mutation.AddedRate(); ok {
		_spec.AddField(loan.FieldRate, field.TypeFloat64, value)
	}
	if value, ok := luo.mutation.Term(); ok {
		_spec.SetField(loan.FieldTerm, field.TypeInt, value)
	}
	if value, ok := luo.mutation.AddedTerm(); ok {
		_spec.AddField(loan.FieldTerm, field.TypeInt, value)
	}
	if luo.mutation.BorrowerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   loan.BorrowerTable,
			Columns: []string{loan.BorrowerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := luo.mutation.BorrowerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   loan.BorrowerTable,
			Columns: []string{loan.BorrowerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Loan{config: luo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, luo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{loan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	luo.mutation.done = true
	return _node, nil
}
