// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/crusyn/loans/ent/loan"
	"github.com/crusyn/loans/ent/predicate"
	"github.com/crusyn/loans/ent/sharedloan"
	"github.com/crusyn/loans/ent/user"
)

// SharedLoanQuery is the builder for querying SharedLoan entities.
type SharedLoanQuery struct {
	config
	ctx        *QueryContext
	order      []sharedloan.OrderOption
	inters     []Interceptor
	predicates []predicate.SharedLoan
	withUser   *UserQuery
	withLoan   *LoanQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SharedLoanQuery builder.
func (slq *SharedLoanQuery) Where(ps ...predicate.SharedLoan) *SharedLoanQuery {
	slq.predicates = append(slq.predicates, ps...)
	return slq
}

// Limit the number of records to be returned by this query.
func (slq *SharedLoanQuery) Limit(limit int) *SharedLoanQuery {
	slq.ctx.Limit = &limit
	return slq
}

// Offset to start from.
func (slq *SharedLoanQuery) Offset(offset int) *SharedLoanQuery {
	slq.ctx.Offset = &offset
	return slq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (slq *SharedLoanQuery) Unique(unique bool) *SharedLoanQuery {
	slq.ctx.Unique = &unique
	return slq
}

// Order specifies how the records should be ordered.
func (slq *SharedLoanQuery) Order(o ...sharedloan.OrderOption) *SharedLoanQuery {
	slq.order = append(slq.order, o...)
	return slq
}

// QueryUser chains the current query on the "user" edge.
func (slq *SharedLoanQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: slq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := slq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := slq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sharedloan.Table, sharedloan.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, sharedloan.UserTable, sharedloan.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(slq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryLoan chains the current query on the "loan" edge.
func (slq *SharedLoanQuery) QueryLoan() *LoanQuery {
	query := (&LoanClient{config: slq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := slq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := slq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sharedloan.Table, sharedloan.FieldID, selector),
			sqlgraph.To(loan.Table, loan.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, sharedloan.LoanTable, sharedloan.LoanColumn),
		)
		fromU = sqlgraph.SetNeighbors(slq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SharedLoan entity from the query.
// Returns a *NotFoundError when no SharedLoan was found.
func (slq *SharedLoanQuery) First(ctx context.Context) (*SharedLoan, error) {
	nodes, err := slq.Limit(1).All(setContextOp(ctx, slq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{sharedloan.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (slq *SharedLoanQuery) FirstX(ctx context.Context) *SharedLoan {
	node, err := slq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SharedLoan ID from the query.
// Returns a *NotFoundError when no SharedLoan ID was found.
func (slq *SharedLoanQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = slq.Limit(1).IDs(setContextOp(ctx, slq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{sharedloan.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (slq *SharedLoanQuery) FirstIDX(ctx context.Context) int {
	id, err := slq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SharedLoan entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SharedLoan entity is found.
// Returns a *NotFoundError when no SharedLoan entities are found.
func (slq *SharedLoanQuery) Only(ctx context.Context) (*SharedLoan, error) {
	nodes, err := slq.Limit(2).All(setContextOp(ctx, slq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{sharedloan.Label}
	default:
		return nil, &NotSingularError{sharedloan.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (slq *SharedLoanQuery) OnlyX(ctx context.Context) *SharedLoan {
	node, err := slq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SharedLoan ID in the query.
// Returns a *NotSingularError when more than one SharedLoan ID is found.
// Returns a *NotFoundError when no entities are found.
func (slq *SharedLoanQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = slq.Limit(2).IDs(setContextOp(ctx, slq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{sharedloan.Label}
	default:
		err = &NotSingularError{sharedloan.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (slq *SharedLoanQuery) OnlyIDX(ctx context.Context) int {
	id, err := slq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SharedLoans.
func (slq *SharedLoanQuery) All(ctx context.Context) ([]*SharedLoan, error) {
	ctx = setContextOp(ctx, slq.ctx, "All")
	if err := slq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SharedLoan, *SharedLoanQuery]()
	return withInterceptors[[]*SharedLoan](ctx, slq, qr, slq.inters)
}

// AllX is like All, but panics if an error occurs.
func (slq *SharedLoanQuery) AllX(ctx context.Context) []*SharedLoan {
	nodes, err := slq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SharedLoan IDs.
func (slq *SharedLoanQuery) IDs(ctx context.Context) (ids []int, err error) {
	if slq.ctx.Unique == nil && slq.path != nil {
		slq.Unique(true)
	}
	ctx = setContextOp(ctx, slq.ctx, "IDs")
	if err = slq.Select(sharedloan.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (slq *SharedLoanQuery) IDsX(ctx context.Context) []int {
	ids, err := slq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (slq *SharedLoanQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, slq.ctx, "Count")
	if err := slq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, slq, querierCount[*SharedLoanQuery](), slq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (slq *SharedLoanQuery) CountX(ctx context.Context) int {
	count, err := slq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (slq *SharedLoanQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, slq.ctx, "Exist")
	switch _, err := slq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (slq *SharedLoanQuery) ExistX(ctx context.Context) bool {
	exist, err := slq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SharedLoanQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (slq *SharedLoanQuery) Clone() *SharedLoanQuery {
	if slq == nil {
		return nil
	}
	return &SharedLoanQuery{
		config:     slq.config,
		ctx:        slq.ctx.Clone(),
		order:      append([]sharedloan.OrderOption{}, slq.order...),
		inters:     append([]Interceptor{}, slq.inters...),
		predicates: append([]predicate.SharedLoan{}, slq.predicates...),
		withUser:   slq.withUser.Clone(),
		withLoan:   slq.withLoan.Clone(),
		// clone intermediate query.
		sql:  slq.sql.Clone(),
		path: slq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (slq *SharedLoanQuery) WithUser(opts ...func(*UserQuery)) *SharedLoanQuery {
	query := (&UserClient{config: slq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	slq.withUser = query
	return slq
}

// WithLoan tells the query-builder to eager-load the nodes that are connected to
// the "loan" edge. The optional arguments are used to configure the query builder of the edge.
func (slq *SharedLoanQuery) WithLoan(opts ...func(*LoanQuery)) *SharedLoanQuery {
	query := (&LoanClient{config: slq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	slq.withLoan = query
	return slq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID int `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SharedLoan.Query().
//		GroupBy(sharedloan.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (slq *SharedLoanQuery) GroupBy(field string, fields ...string) *SharedLoanGroupBy {
	slq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SharedLoanGroupBy{build: slq}
	grbuild.flds = &slq.ctx.Fields
	grbuild.label = sharedloan.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID int `json:"user_id,omitempty"`
//	}
//
//	client.SharedLoan.Query().
//		Select(sharedloan.FieldUserID).
//		Scan(ctx, &v)
func (slq *SharedLoanQuery) Select(fields ...string) *SharedLoanSelect {
	slq.ctx.Fields = append(slq.ctx.Fields, fields...)
	sbuild := &SharedLoanSelect{SharedLoanQuery: slq}
	sbuild.label = sharedloan.Label
	sbuild.flds, sbuild.scan = &slq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SharedLoanSelect configured with the given aggregations.
func (slq *SharedLoanQuery) Aggregate(fns ...AggregateFunc) *SharedLoanSelect {
	return slq.Select().Aggregate(fns...)
}

func (slq *SharedLoanQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range slq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, slq); err != nil {
				return err
			}
		}
	}
	for _, f := range slq.ctx.Fields {
		if !sharedloan.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if slq.path != nil {
		prev, err := slq.path(ctx)
		if err != nil {
			return err
		}
		slq.sql = prev
	}
	return nil
}

func (slq *SharedLoanQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SharedLoan, error) {
	var (
		nodes       = []*SharedLoan{}
		_spec       = slq.querySpec()
		loadedTypes = [2]bool{
			slq.withUser != nil,
			slq.withLoan != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SharedLoan).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SharedLoan{config: slq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, slq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := slq.withUser; query != nil {
		if err := slq.loadUser(ctx, query, nodes, nil,
			func(n *SharedLoan, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := slq.withLoan; query != nil {
		if err := slq.loadLoan(ctx, query, nodes, nil,
			func(n *SharedLoan, e *Loan) { n.Edges.Loan = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (slq *SharedLoanQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*SharedLoan, init func(*SharedLoan), assign func(*SharedLoan, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*SharedLoan)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (slq *SharedLoanQuery) loadLoan(ctx context.Context, query *LoanQuery, nodes []*SharedLoan, init func(*SharedLoan), assign func(*SharedLoan, *Loan)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*SharedLoan)
	for i := range nodes {
		fk := nodes[i].LoanID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(loan.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "loan_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (slq *SharedLoanQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := slq.querySpec()
	_spec.Node.Columns = slq.ctx.Fields
	if len(slq.ctx.Fields) > 0 {
		_spec.Unique = slq.ctx.Unique != nil && *slq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, slq.driver, _spec)
}

func (slq *SharedLoanQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(sharedloan.Table, sharedloan.Columns, sqlgraph.NewFieldSpec(sharedloan.FieldID, field.TypeInt))
	_spec.From = slq.sql
	if unique := slq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if slq.path != nil {
		_spec.Unique = true
	}
	if fields := slq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sharedloan.FieldID)
		for i := range fields {
			if fields[i] != sharedloan.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if slq.withUser != nil {
			_spec.Node.AddColumnOnce(sharedloan.FieldUserID)
		}
		if slq.withLoan != nil {
			_spec.Node.AddColumnOnce(sharedloan.FieldLoanID)
		}
	}
	if ps := slq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := slq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := slq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := slq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (slq *SharedLoanQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(slq.driver.Dialect())
	t1 := builder.Table(sharedloan.Table)
	columns := slq.ctx.Fields
	if len(columns) == 0 {
		columns = sharedloan.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if slq.sql != nil {
		selector = slq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if slq.ctx.Unique != nil && *slq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range slq.predicates {
		p(selector)
	}
	for _, p := range slq.order {
		p(selector)
	}
	if offset := slq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := slq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SharedLoanGroupBy is the group-by builder for SharedLoan entities.
type SharedLoanGroupBy struct {
	selector
	build *SharedLoanQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (slgb *SharedLoanGroupBy) Aggregate(fns ...AggregateFunc) *SharedLoanGroupBy {
	slgb.fns = append(slgb.fns, fns...)
	return slgb
}

// Scan applies the selector query and scans the result into the given value.
func (slgb *SharedLoanGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, slgb.build.ctx, "GroupBy")
	if err := slgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SharedLoanQuery, *SharedLoanGroupBy](ctx, slgb.build, slgb, slgb.build.inters, v)
}

func (slgb *SharedLoanGroupBy) sqlScan(ctx context.Context, root *SharedLoanQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(slgb.fns))
	for _, fn := range slgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*slgb.flds)+len(slgb.fns))
		for _, f := range *slgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*slgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := slgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SharedLoanSelect is the builder for selecting fields of SharedLoan entities.
type SharedLoanSelect struct {
	*SharedLoanQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sls *SharedLoanSelect) Aggregate(fns ...AggregateFunc) *SharedLoanSelect {
	sls.fns = append(sls.fns, fns...)
	return sls
}

// Scan applies the selector query and scans the result into the given value.
func (sls *SharedLoanSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sls.ctx, "Select")
	if err := sls.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SharedLoanQuery, *SharedLoanSelect](ctx, sls.SharedLoanQuery, sls, sls.inters, v)
}

func (sls *SharedLoanSelect) sqlScan(ctx context.Context, root *SharedLoanQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sls.fns))
	for _, fn := range sls.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
