// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/crusyn/loans/ent/predicate"
	"github.com/crusyn/loans/ent/sharedloan"
)

// SharedLoanDelete is the builder for deleting a SharedLoan entity.
type SharedLoanDelete struct {
	config
	hooks    []Hook
	mutation *SharedLoanMutation
}

// Where appends a list predicates to the SharedLoanDelete builder.
func (sld *SharedLoanDelete) Where(ps ...predicate.SharedLoan) *SharedLoanDelete {
	sld.mutation.Where(ps...)
	return sld
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (sld *SharedLoanDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, sld.sqlExec, sld.mutation, sld.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (sld *SharedLoanDelete) ExecX(ctx context.Context) int {
	n, err := sld.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (sld *SharedLoanDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(sharedloan.Table, sqlgraph.NewFieldSpec(sharedloan.FieldID, field.TypeInt))
	if ps := sld.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, sld.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	sld.mutation.done = true
	return affected, err
}

// SharedLoanDeleteOne is the builder for deleting a single SharedLoan entity.
type SharedLoanDeleteOne struct {
	sld *SharedLoanDelete
}

// Where appends a list predicates to the SharedLoanDelete builder.
func (sldo *SharedLoanDeleteOne) Where(ps ...predicate.SharedLoan) *SharedLoanDeleteOne {
	sldo.sld.mutation.Where(ps...)
	return sldo
}

// Exec executes the deletion query.
func (sldo *SharedLoanDeleteOne) Exec(ctx context.Context) error {
	n, err := sldo.sld.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{sharedloan.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (sldo *SharedLoanDeleteOne) ExecX(ctx context.Context) {
	if err := sldo.Exec(ctx); err != nil {
		panic(err)
	}
}
