// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/crusyn/loans/ent/loan"
	"github.com/crusyn/loans/ent/sharedloan"
	"github.com/crusyn/loans/ent/user"
)

// SharedLoanCreate is the builder for creating a SharedLoan entity.
type SharedLoanCreate struct {
	config
	mutation *SharedLoanMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (slc *SharedLoanCreate) SetUserID(i int) *SharedLoanCreate {
	slc.mutation.SetUserID(i)
	return slc
}

// SetLoanID sets the "loan_id" field.
func (slc *SharedLoanCreate) SetLoanID(i int) *SharedLoanCreate {
	slc.mutation.SetLoanID(i)
	return slc
}

// SetUser sets the "user" edge to the User entity.
func (slc *SharedLoanCreate) SetUser(u *User) *SharedLoanCreate {
	return slc.SetUserID(u.ID)
}

// SetLoan sets the "loan" edge to the Loan entity.
func (slc *SharedLoanCreate) SetLoan(l *Loan) *SharedLoanCreate {
	return slc.SetLoanID(l.ID)
}

// Mutation returns the SharedLoanMutation object of the builder.
func (slc *SharedLoanCreate) Mutation() *SharedLoanMutation {
	return slc.mutation
}

// Save creates the SharedLoan in the database.
func (slc *SharedLoanCreate) Save(ctx context.Context) (*SharedLoan, error) {
	return withHooks(ctx, slc.sqlSave, slc.mutation, slc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (slc *SharedLoanCreate) SaveX(ctx context.Context) *SharedLoan {
	v, err := slc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (slc *SharedLoanCreate) Exec(ctx context.Context) error {
	_, err := slc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (slc *SharedLoanCreate) ExecX(ctx context.Context) {
	if err := slc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (slc *SharedLoanCreate) check() error {
	if _, ok := slc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "SharedLoan.user_id"`)}
	}
	if _, ok := slc.mutation.LoanID(); !ok {
		return &ValidationError{Name: "loan_id", err: errors.New(`ent: missing required field "SharedLoan.loan_id"`)}
	}
	if _, ok := slc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "SharedLoan.user"`)}
	}
	if _, ok := slc.mutation.LoanID(); !ok {
		return &ValidationError{Name: "loan", err: errors.New(`ent: missing required edge "SharedLoan.loan"`)}
	}
	return nil
}

func (slc *SharedLoanCreate) sqlSave(ctx context.Context) (*SharedLoan, error) {
	if err := slc.check(); err != nil {
		return nil, err
	}
	_node, _spec := slc.createSpec()
	if err := sqlgraph.CreateNode(ctx, slc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	slc.mutation.id = &_node.ID
	slc.mutation.done = true
	return _node, nil
}

func (slc *SharedLoanCreate) createSpec() (*SharedLoan, *sqlgraph.CreateSpec) {
	var (
		_node = &SharedLoan{config: slc.config}
		_spec = sqlgraph.NewCreateSpec(sharedloan.Table, sqlgraph.NewFieldSpec(sharedloan.FieldID, field.TypeInt))
	)
	if nodes := slc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sharedloan.UserTable,
			Columns: []string{sharedloan.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := slc.mutation.LoanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sharedloan.LoanTable,
			Columns: []string{sharedloan.LoanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(loan.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.LoanID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SharedLoanCreateBulk is the builder for creating many SharedLoan entities in bulk.
type SharedLoanCreateBulk struct {
	config
	err      error
	builders []*SharedLoanCreate
}

// Save creates the SharedLoan entities in the database.
func (slcb *SharedLoanCreateBulk) Save(ctx context.Context) ([]*SharedLoan, error) {
	if slcb.err != nil {
		return nil, slcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(slcb.builders))
	nodes := make([]*SharedLoan, len(slcb.builders))
	mutators := make([]Mutator, len(slcb.builders))
	for i := range slcb.builders {
		func(i int, root context.Context) {
			builder := slcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SharedLoanMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, slcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, slcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, slcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (slcb *SharedLoanCreateBulk) SaveX(ctx context.Context) []*SharedLoan {
	v, err := slcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (slcb *SharedLoanCreateBulk) Exec(ctx context.Context) error {
	_, err := slcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (slcb *SharedLoanCreateBulk) ExecX(ctx context.Context) {
	if err := slcb.Exec(ctx); err != nil {
		panic(err)
	}
}
