definitions:
  handlers.loanMonthResponseItem:
    properties:
      month:
        type: integer
      monthlyPayment:
        type: number
      remainingBalance:
        type: number
    type: object
  handlers.loanMonthSummaryResponse:
    properties:
      endingBalance:
        type: number
      totalInterestPaid:
        type: number
      totalPrincipalPaid:
        type: number
    type: object
  handlers.loanResponse:
    properties:
      amount:
        type: number
      id:
        type: integer
      rate:
        type: number
      term:
        type: integer
    type: object
  handlers.loanShareRequest:
    properties:
      id:
        type: integer
    type: object
  handlers.newLoanRequest:
    properties:
      amount:
        type: number
      borrowerID:
        type: integer
      months:
        type: integer
      rate:
        type: number
    type: object
  handlers.newLoanResponse:
    properties:
      newLoanId:
        type: integer
    type: object
  handlers.newUserRequest:
    properties:
      address:
        type: string
      name:
        type: string
      social:
        type: string
    type: object
  handlers.newUserResponse:
    properties:
      newUserId:
        type: integer
    type: object
info:
  contact: {}
paths:
  /loan/:
    post:
      consumes:
      - application/json
      description: Creates a Loan associated with a specific borrower
      parameters:
      - description: New Loan Request
        in: body
        name: newLoanRequest
        required: true
        schema:
          $ref: '#/definitions/handlers.newLoanRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.newLoanResponse'
      summary: Creates Loan
  /loan/{loanid}:
    get:
      consumes:
      - application/json
      description: Gets Loan Terms
      parameters:
      - description: Loan Id
        in: path
        name: loanid
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.loanResponse'
      summary: Gets Loan Information
  /loan/{loanid}/month/{month}:
    get:
      consumes:
      - application/json
      description: Gets aggregate loan data given a particular month
      parameters:
      - description: Loan Id
        in: path
        name: loanid
        required: true
        type: integer
      - description: Month Number
        in: path
        name: month
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.loanMonthSummaryResponse'
      summary: Gets Loan Month Summary
  /loan/{loanid}/schedule:
    get:
      consumes:
      - application/json
      description: Gets the loans schedule by month
      parameters:
      - description: Loan Id
        in: path
        name: loanid
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handlers.loanMonthResponseItem'
            type: array
      summary: Gets Loan Schedule
  /loan/{loanid}/share:
    post:
      consumes:
      - application/json
      description: Shares loan with another user that is not the borrower
      parameters:
      - description: Loan Id
        in: path
        name: loanid
        required: true
        type: integer
      - description: Share User Request
        in: body
        name: loanShareRequest
        required: true
        schema:
          $ref: '#/definitions/handlers.loanShareRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Shares Loan
  /user:
    post:
      consumes:
      - application/json
      description: Creates User given a `newUserRequest`
      parameters:
      - description: New User Request
        in: body
        name: newUserRequest
        required: true
        schema:
          $ref: '#/definitions/handlers.newUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.newUserResponse'
      summary: Creates User
  /user/{userid}/loans:
    get:
      consumes:
      - application/json
      description: |-
        Gets Loans associated with a specific user.  The user may be the borrower
        or the loan may be shared with that user.
      parameters:
      - description: User Id
        in: path
        name: userid
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handlers.loanResponse'
            type: array
      summary: Gets Loans by User
swagger: "2.0"
